1. Реализуйте сингулярное матричные разложения (не используя готовые решения вроде numpy.linalg.svd, или numpy.linalg.eig для поиска собственных векторов и чисел);
2. Выберите произвольный многомерный массив данных, содержащий минимум 5
признаков;
3. Используйте написанный метод сингулярного разложения для получения матрицы преобразований данных к главным компонентам и значения объясняемых
дисперсий. Опишите ограничения применимости реализаций SVD к решению
данной задачи;
4. Определите достаточное число компонент для описания процесса, визуализируйте данные и проведите анализ полученных компонент;
5. (Дополнительное задание) Реализуйте методы сингулярного разложения матрицы, имеющие меньшую вычислительную сложность, чем классический подход, основанный на собственных векторах и собственных числах матрицы XT X

In [35]:
import numpy as np
import math


In [36]:
def eig(A):
    """мой методы вычисления собсвтенных чисел
    используется метод вращений
    U = [[]]
    
    Ut*A*U = V
    """
    
    
    """
for (unsigned int i=0; i<N-1; ++i) 
    {
    for (unsigned int j=i+2; j<N; ++j)               
        {
            t = 2*matr[i][j]/(matr[i][i] - matr[j][j]);
            phi = 0.5 * atan(t);
            c = cos(phi);
            s = sin(phi);
 
            bii = c*c*matr[i][i] + 2*c*s*matr[i][j] + s*s*matr[j][j];
            bij = s*c*(matr[j][j] - matr[i][i]) + matr[i][j] * (c*c - s*s);
            bjj = s*s*matr[i][i] + c*c*matr[j][j] - 2*c*s*matr[i][j];
            bji = bij;
 
            matr[i][i] = bii;
            matr[i][j] = bij;
            matr[j][i] = bji;
            matr[j][j] = bjj;
        }
    }

    Returns:
        _type_: _description_
    """
    B = A.copy()
    N = A.shape[0]
    for i in range(0, N-1):
        for j in range(i+2, N):
            t = 2*A[i][j] / A[i][i] - A[j][j]
            phi = 0.5 * math.atan(t)
            c = math.cos(phi)
            s = math.sin(phi)
            
            bii = c*c*A[i][i] + 2*c*s*A[i][j] + s*s*A[j][j]
            bij = s*c*A[j][j] - A[i][i] + A[i][j]* (c*c - s*s)
            bjj = s*s*A[i][i] + c*c*A[j][j] - 2*c*s*A[i][j]
            bji = bij
            
            B[i][i] = bii
            B[i][j] = bij
            B[j][i] = bji
            B[j][j] = bjj
            
    print(A, B)


    

def svd(data):
    """мой метод сингулярного разложения"""
    
    A = data # исходная матрица А
    At = A.transpose() # транспонированная матрица А
    AtA = np.dot(At, A) # произведение транспонированной матрицы At на А
    
    """"""
    
    """
    [[2-x 0 -1]
    [0 2-x -1]
    [-1 -1 1-x]]
    
    (2-x) * x(-3+x) = 0
    """


    return eig(AtA)
    
    

test = np.array([[-1, 1, 0], [-1, -1, 1]])
print(svd(test))

[[ 2  0 -1]
 [ 0  2 -1]
 [-1 -1  1]] [[ 2  0 -2]
 [ 0  2 -1]
 [-2 -1  0]]
None
